### ISSUE TITLE
set ES heap size to 1g

### ISSUE THREAD

**Issue by ghukill** [WSULib/combine-vm#9]
Under `/etc/elasticsearch/jvm.options`, set heap size to `1g`:
```
# Xms represents the initial size of total heap space
# Xmx represents the maximum size of total heap space

-Xms1g
-Xmx1g
```

Possible to `sed` this during provisioning, or, create `jvm.options` in advance that is copied over after ES installation.

**Comment by colehudson** [comment]
Fixed. `jvm.options` is copied over from `config/files` during ES provisioning.
